# Generated by Django 6.0.5 on 2026-05-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenTimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Study', 'Study'), ('Social', 'Social'), ('Gaming', 'Gaming'), ('Work', 'Work'), ('Entertainment', 'Entertainment')], max_length=50)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
